# Generated by Django 2.2.24 on 2021-09-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toolsofthemind", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tomcoursesubgroups",
            name="course_subgroup",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="tomcoursesubgroups",
            name="ordinal_position",
            field=models.IntegerField(
                help_text="The ordinal position of this record in relation to all otherSub Group items for this Tools of the Mind Course Group."
            ),
        ),
    ]
